# Generated by Django 5.0.14 on 2026-06-30 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location_name', models.CharField(max_length=255, verbose_name='Current Location Name')),
                ('current_location_lat', models.FloatField(verbose_name='Current Location Latitude')),
                ('current_location_lng', models.FloatField(verbose_name='Current Location Longitude')),
                ('pickup_location_name', models.CharField(max_length=255, verbose_name='Pickup Location Name')),
                ('pickup_location_lat', models.FloatField(verbose_name='Pickup Location Latitude')),
                ('pickup_location_lng', models.FloatField(verbose_name='Pickup Location Longitude')),
                ('dropoff_location_name', models.CharField(max_length=255, verbose_name='Dropoff Location Name')),
                ('dropoff_location_lat', models.FloatField(verbose_name='Dropoff Location Latitude')),
                ('dropoff_location_lng', models.FloatField(verbose_name='Dropoff Location Longitude')),
                ('start_cycle_used_hours', models.FloatField(default=0.0, verbose_name='Start Cycle Used Hours')),
                ('total_distance_miles', models.FloatField(default=0.0, verbose_name='Total Distance (Miles)')),
                ('total_duration_hours', models.FloatField(default=0.0, verbose_name='Total Duration (Hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='trips_created_4fa010_idx')],
            },
        ),
        migrations.CreateModel(
            name='ELDLogDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField(verbose_name='Log Date')),
                ('driving_hours', models.FloatField(default=0.0, verbose_name='Driving Hours')),
                ('on_duty_hours', models.FloatField(default=0.0, verbose_name='On Duty (Non-Driving) Hours')),
                ('off_duty_hours', models.FloatField(default=0.0, verbose_name='Off Duty Hours')),
                ('sleeper_berth_hours', models.FloatField(default=0.0, verbose_name='Sleeper Berth Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_days', to='trip_planner.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'ELD Log Day',
                'verbose_name_plural': 'ELD Log Days',
                'db_table': 'eld_log_days',
                'ordering': ['log_date'],
            },
        ),
        migrations.CreateModel(
            name='ELDEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY_ND', 'On Duty (Non-Driving)')], max_length=20, verbose_name='Duty Status')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('location_name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('eld_log_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trip_planner.eldlogday', verbose_name='ELD Log Day')),
            ],
            options={
                'verbose_name': 'ELD Event',
                'verbose_name_plural': 'ELD Events',
                'db_table': 'eld_events',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['eld_log_day', 'start_time'], name='eld_events_eld_log_3c1ab5_idx'), models.Index(fields=['status'], name='eld_events_status_833d70_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('ORIGIN', 'Origin'), ('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff'), ('REST_STOP', 'Rest Stop'), ('FUEL_STOP', 'Fuel Stop'), ('SLEEP_STOP', 'Sleep Stop')], max_length=20, verbose_name='Stop Type')),
                ('location_name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival Time')),
                ('duration_hours', models.FloatField(verbose_name='Duration (Hours)')),
                ('distance_from_start_miles', models.FloatField(default=0.0, verbose_name='Distance From Start (Miles)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trip_planner.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Stop',
                'verbose_name_plural': 'Stops',
                'db_table': 'stops',
                'ordering': ['arrival_time'],
                'indexes': [models.Index(fields=['trip', 'arrival_time'], name='stops_trip_id_f3e192_idx'), models.Index(fields=['stop_type'], name='stops_stop_ty_f14096_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='eldlogday',
            index=models.Index(fields=['trip', 'log_date'], name='eld_log_day_trip_id_b48da2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eldlogday',
            unique_together={('trip', 'log_date')},
        ),
    ]
