# Generated by Django 5.0.14 on 2026-06-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['current_location_name'], name='trips_current_b9571a_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['pickup_location_name'], name='trips_pickup__6dda2e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['dropoff_location_name'], name='trips_dropoff_bebba0_idx'),
        ),
    ]
